---
title: "Barcoding graph code"
author: "Daniel Hu"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
# reading the class data 
class_data <- read_csv("2022_EEB382_Barcoding_ClassData.csv")
```

How often are fish misidentified/mislabelled? What are some plausible reasons 
for misidentification/mislabelling

```{r}
new_data <- class_data %>% 
  group_by(`Labelled Correctly`) %>% 
  tally()
new_data
```
```{r}
new_data %>% 
  ggplot(aes(y=n, x=`Labelled Correctly`, fill = `Labelled Correctly`)) + geom_bar(stat = "identity") + 
  labs(title = "Number of Samples Labelled Correctly as Verified By Barcoding", x=
         "Was the Fish Labelled Correctly?", y= "Number of Samples") + geom_text(aes(label=n), vjust = -0.2) +theme_classic()
```

What are the frequencies of the IUCN categories and what does this suggest about 
the sustainability of the Toronto fish trade?  

```{r}
class_data %>% 
  mutate(status = toupper(`IUCN status`)) %>% 
  group_by(status) %>% 
  tally() %>% 
  ggplot(aes(y=n, x= status, fill = status)) + geom_bar(stat = "identity")+ 
   labs(title = 
  "IUCN Status of Sampled Fish Species", x = "IUCN Category", y = "Number of 
  Samples") + geom_text(aes(label=n), vjust = -0.1) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```
```{r}
class_data %>% 
  mutate(status = toupper(`IUCN status`)) %>% 
  group_by(status) %>% 
  tally() %>% 
  ggplot(aes(y=n, x= "", fill = status)) + geom_bar(stat = "identity")+
  theme(axis.text.x=element_blank())+ geom_text(aes(y=status + c(0, cumsum(n)[-length(n)])), label=percent(value/100), size =)
  coord_polar("y", start=0) +
   labs(title = 
  "IUCN Status of Sampled Fish Species", x = "IUCN Category", y = "Number of 
  Samples")
```


